authentik:
  postgresql:
    host: cnpg-cluster-rw.cnpg.svc.cluster
    port: 5432
    user: file:///postgres-creds/username
    password: file:///postgres-creds/password
  secret_key: file:///authentik-creds/secretKey
server:
  service:
    nodePortHttp: 33080
    nodePortHttps: 33443
  volumes:
    - name: postgres-creds
      secret:
        secretName: authentik-postgres-credentials
    - name: authentik-creds
      secret:
        secretName: authentik-secret-key
  volumeMounts:
    - name: postgres-creds
      mountPath: /postgres-creds
      readOnly: true
    - name: authentik-creds
      mountPath: /authentik-creds
      readOnly: true
worker:
  volumes:
    - name: postgres-creds
      secret:
        secretName: authentik-postgres-credentials
    - name: authentik-creds
      secret:
        secretName: authentik-secret-key
  volumeMounts:
    - name: postgres-creds
      mountPath: /postgres-creds
      readOnly: true
    - name: authentik-creds
      mountPath: /authentik-creds
      readOnly: true